import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // next-env.d.ts is generated by Next on every build and its triple-slash references
    // are not ours to change. Leaving it in meant `npx eslint .` always reported an error
    // nobody could fix — and an always-failing gate is one people stop reading, which is
    // exactly how a real lint failure reached a deploy.
    ignores: [".next/**", "node_modules/**", "src/generated/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
